name: align
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  shared_preferences: ^2.5.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  smooth_page_indicator: ^2.0.1
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  intl: ^0.19.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test: any
  build_runner: ^2.10.4
  freezed: ^3.2.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/games_background/
    - assets/images/on_boarding/